DesarrollodeProyectos/Entities/Material.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace DesarrollodeProyectos.Identity
{
    public class Material
    {
        public Material()
        {
            Name = string.Empty;
            Description = string.Empty;
            Shirts = new List<Shirt>();
            Sweaters = new List<Sweater>();
            Caps = new List<Cap>();
        }

        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public int Quantity { get; set; }
 

        public bool IsActive { get; set; } = true;

        public DateTime CreationTime { get; set; } = DateTime.Now;

        public string? ImageUrl { get; set; }

        public Guid? SupplierId { get; set; } 
        public Supplier? Supplier { get; set; }

        public List<Shirt> Shirts { get; set; }
        public List<Sweater> Sweaters { get; set; }
        public List<Cap> Caps { get; set; }
        
    }
}

DesarrollodeProyectos/Controllers/MaterialController.cs
using DesarrollodeProyectos.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DesarrollodeProyectos.Controllers
{
    public class MaterialController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<MaterialController> _logger;

        public MaterialController(ApplicationDbContext context, ILogger<MaterialController> logger)
        {
            _logger = logger;
            _context = context;
        }

        // Acción para agregar un nuevo material
        public async Task<IActionResult> MaterialAdd()
        {
            var model = new MaterialModel
            {
                // Cargar listas de opciones para los campos
                ShirtList = await _context.Shirts
                    .Where(s => s.IsActive)
                    .Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.Name
                    }).ToListAsync(),
                SweaterList = await _context.Sweaters
                    .Where(s => s.IsActive)
                    .Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.Name
                    }).ToListAsync(),
                CapList = await _context.Caps
                    .Where(c => c.IsActive)
                    .Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    }).ToListAsync(),
                SupplierList = await _context.Suppliers
                    .Where(s => s.IsActive)
                    .Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.Name
                    }).ToListAsync()
            };

            return View(model);
        }

        // Acción POST para agregar un nuevo material
        [HttpPost]
        public async Task<IActionResult> MaterialAdd(MaterialModel materialModel)
        {
            if (!ModelState.IsValid)
            {
                _logger.LogError("El modelo de material no es válido");
                return View(materialModel);
            }

            var materialEntity = new Material
            {
                Id = Guid.NewGuid(),
                Name = materialModel.Name,
                Description = materialModel.Description,
                Quantity = materialModel.Quantity,
                CreationTime = DateTime.Now,
                IsActive = materialModel.IsActive,
                SupplierId = materialModel.SupplierId
            };

            _context.Materials.Add(materialEntity);
            await _context.SaveChangesAsync();

            return RedirectToAction("MaterialList"); // Redirige a la lista de materiales
        }

        // Acción para listar los materiales
        public async Task<IActionResult> MaterialList()
        {
            var materials = await _context.Materials
                                   .Where(m => m.IsActive)
                                   .ToListAsync();

            var materialModels = materials.Select(m => new MaterialModel
            {
                Id = m.Id,
                Name = m.Name,
                Description = m.Description,
                Quantity = m.Quantity,
                CreationTime = m.CreationTime,
                IsActive = m.IsActive,
                SupplierId = m.SupplierId
            }).ToList();

            return View(materialModels); 
        }

        // Acción para editar un material
        public async Task<IActionResult> MaterialEdit(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var material = await _context.Materials.FindAsync(id);

            if (material == null)
            {
                return NotFound();
            }

            var materialModel = new MaterialModel
            {
                Id = material.Id,
                Name = material.Name,
                Description = material.Description,
                Quantity = material.Quantity,
                CreationTime = material.CreationTime,
                IsActive = material.IsActive,
                SupplierId = material.SupplierId,
                // Cargar listas de opciones
                ShirtList = await _context.Shirts
                    .Where(s => s.IsActive)
                    .Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.Name
                    }).ToListAsync(),
                SweaterList = await _context.Sweaters
                    .Where(s => s.IsActive)
                    .Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.Name
                    }).ToListAsync(),
                CapList = await _context.Caps
                    .Where(c => c.IsActive)
                    .Select(c => new SelectListItem
                    {
                        Value = c.Id.ToString(),
                        Text = c.Name
                    }).ToListAsync(),
                SupplierList = await _context.Suppliers
                    .Where(s => s.IsActive)
                    .Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.Name
                    }).ToListAsync()
            };

            return View(materialModel);
        }

        // Acción POST para editar un material
        [HttpPost]
        public async Task<IActionResult> MaterialEdit(MaterialModel materialModel)
        {
            if (!ModelState.IsValid)
            {
                _logger.LogError("El modelo de material no es válido");
                return View(materialModel);
            }

            var materialEntity = await _context.Materials.FindAsync(materialModel.Id);

            if (materialEntity == null)
            {
                return NotFound();
            }

            // Actualizar material
            materialEntity.Name = materialModel.Name;
            materialEntity.Description = materialModel.Description;
            materialEntity.Quantity = materialModel.Quantity;
            materialEntity.SupplierId = materialModel.SupplierId;

            _context.Materials.Update(materialEntity);
            await _context.SaveChangesAsync();

            return RedirectToAction("MaterialList"); // Redirige a la lista de materiales
        }

        // Acción para eliminar un material (GET)
        public async Task<IActionResult> MaterialDelete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var material = await _context.Materials.FindAsync(id);

            if (material == null)
            {
                return NotFound();
            }

            var model = new MaterialModel
            {
                Id = material.Id,
                Name = material.Name,
                Description = material.Description,
                Quantity = material.Quantity
            };

            return View("MaterialDeleted", model); // Devolver vista MaterialDeleted.cshtml con el modelo
        }

        // Acción POST para eliminar un material
        [HttpPost]
        public async Task<IActionResult> MaterialDelete(MaterialModel materialModel)
        {
            var materialEntity = await _context.Materials.FindAsync(materialModel.Id);

            if (materialEntity == null)
            {
                return NotFound();
            }

            // Marcar el material como inactivo
            materialEntity.IsActive = false;

            // Guardar cambios en la base de datos
            _context.Update(materialEntity);
            await _context.SaveChangesAsync();

            return RedirectToAction("MaterialList"); // Redirige a la lista de materiales
        }
    }
}

DesarrollodeProyectos/Views/Material/MaterialAdd.cshtml
@using DesarrollodeProyectos.Identity
@model MaterialModel

@{
    ViewData["Title"] = "Alta de Material";
}

<h1>Alta de Material</h1>

<form asp-action="MaterialAdd" asp-controller="Material" enctype="multipart/form-data">

    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="Name">
        <label asp-for="Name">Nombre del material</label>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="Description">
        <label asp-for="Description">Descripción del material</label>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-outline-primary">Guardar</button>
    <a class="btn btn-outline-secondary" asp-action="MaterialList" asp-controller="Material">Regresar</a>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

DesarrollodeProyectos/Views/Material/MaterialDelete.cshtml
@using DesarrollodeProyectos.Identity
@model MaterialModel

@{
    ViewData["Title"] = "Borrar Material";
}

<h3 class="mb-3">¿Está seguro que desea borrar este material?</h3>

<form asp-controller="Material" asp-action="MaterialDelete" method="post">

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Información del Material</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">¿Está seguro que desea borrar este material?</h6>
            <p class="card-text">Material: @Model.Name</p>
            <p class="card-text">Descripción: @Model.Description</p>
        </div>
    </div>

    <!-- Campo oculto para enviar el Id del material -->
    <input type="hidden" asp-for="Id" />
    
    <!-- Botón para confirmar la eliminación -->
    <button type="submit" class="btn btn-outline-danger">Borrar</button>

    <!-- Botón para cancelar -->
    <a class="btn btn-outline-secondary" asp-action="MaterialList" asp-controller="Material">Cancelar</a>
</form>

DesarrollodeProyectos/Views/Material/MaterialDeleted.cshtml
@using DesarrollodeProyectos.Identity
@model MaterialModel

@{
    ViewData["Title"] = "Borrar Material";
}

<h3 class="mb-3">¿Está seguro que desea borrar este material?</h3>

<form asp-controller="Material" asp-action="MaterialDelete" method="post">

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Información del Material</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">¿Está seguro que desea borrar este material?</h6>
            <p class="card-text">Material: @Model.Name</p>
            <p class="card-text">Descripción: @Model.Description</p>
        </div>
    </div>

    <!-- Campo oculto para enviar el Id del material -->
    <input type="hidden" asp-for="Id" />
    
    <!-- Botón para confirmar la eliminación -->
    <button type="submit" class="btn btn-outline-danger">Borrar</button>

    <!-- Botón para cancelar -->
    <a class="btn btn-outline-secondary" asp-action="MaterialList" asp-controller="Material">Cancelar</a>
</form>

DesarrollodeProyectos/Views/Material/MaterialEdit.cshtml
@using DesarrollodeProyectos.Identity
@model MaterialModel

@{
    ViewData["Title"] = "Editar Material";
}

<h1 style="text-align: center;">@ViewData["Title"]</h1>

<form asp-action="MaterialEdit" asp-controller="Material">
    <input type="hidden" asp-for="Id">

    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="Name" placeholder="Nombre del material">
        <label asp-for="Name">Nombre</label>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="Description" placeholder="Descripción del material">
        <label asp-for="Description">Descripción</label>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-outline-primary">Guardar</button>
    <a class="btn btn-outline-secondary" asp-action="MaterialList" asp-controller="Material">Regresar</a>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

DesarrollodeProyectos/Views/Material/MaterialList.cshtml
@model List<DesarrollodeProyectos.Identity.MaterialModel>

@{
    ViewData["Title"] = "Lista de Materiales";
    int numero = 0;
}

<h1 style="text-align: center;">@ViewData["Title"]</h1>

<p>
    <a href="@Url.Action("MaterialAdd", "Material")" class="btn btn-outline-primary">Agregar Nuevo Material</a>
</p>

<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Descripción</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var material in Model)
        {
            numero++;
            <tr>
                <th scope="row">@numero</th>
                <td>@material.Name</td>
                <td>@material.Description</td>
                <td>
                    <a href="@Url.Action("MaterialEdit", "Material", new { id = material.Id })" class="btn btn-outline-info btn-sm">Editar</a>
                    <a href="@Url.Action("MaterialDelete", "Material", new { id = material.Id })" class="btn btn-outline-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar este material?');">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>